name: CI

on:
  # 在master分支发生push事件时触发。
  push:
    branches:
      - main
  # 手动触发构建
  workflow_dispatch:

# 设置环境变量
env:
  # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）
  TZ: Asia/Shanghai

jobs:
  build:
    # 运行在虚拟机环境ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
      # 检出仓库
      - name: Checkout
        uses: actions/checkout@v3

      # 安装 Node
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # 获取node_modules缓存
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.node-version }}-${{ env.cache-name }}-

      # 缓存未命中则安装依赖
      - if: ${{ steps.cache-node-modules.outputs.cache-hit == false }}
        name: Install dependencies
        run: npm install

      # 运行部署脚本
      - name: Run deploy shell
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN_4_GITHUB }}
        run: bash deploy.sh
